### ISSUE TITLE
AttributeError: module 'types' has no attribute 'CellType'

### ISSUE THREAD

**Issue by Yuanzizizi** [ethz-asl/navrep#2]
Hi, 
I want to test out this environment with the pretrained models in your repository. 
After I run "python -m navrep.scripts.cross_test_navreptrain_in_ianenv --backend VAE_LSTM --encoding V_ONLY --render", I get this:

`
2022-11-11 16:58:51.825066: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-11-11 16:58:51.835343: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112000000 Hz
2022-11-11 16:58:51.837113: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x83e3410 executing computations on platform Host. Devices:
2022-11-11 16:58:51.837227: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2022-11-11 16:58:51.931099: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
  0%|                                                                                                                                                                        | 0/3 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/scripts/cross_test_navreptrain_in_ianenv.py", line 101, in <module>
    c_model = PPO2.load(c_model_path)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 936, in load
    data, params = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 666, in _load_from_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/save_util.py", line 120, in json_to_data
    base64.b64decode(serialization.encode())
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 384, in <module>
    class CloudPickler(Pickler):
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 406, in CloudPickler
    dispatch[types.CellType] = _cell_reduce
**AttributeError: module 'types' has no attribute 'CellType'**
`

Is there an error in the **version** of my installation? I hope to get your help. Thank you~~

**Comment by Yuanzizizi** [comment]
Here's the full log:

Ros was not found, disabled.
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/tutu/navrepvenv/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/__init__.py:33: UserWarning: stable-baselines is in maintenance mode, please use [Stable-Baselines3 (SB3)](https://github.com/DLR-RM/stable-baselines3) for an up-to-date version. You can find a [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html) in SB3 documentation.
  "stable-baselines is in maintenance mode, please use [Stable-Baselines3 (SB3)](https://github.com/DLR-RM/stable-baselines3) for an up-to-date version. You can find a [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html) in SB3 documentation."

-------------------------------
             ARGS              
-- no_gpu : False
-- debug : False
-- dry_run : False
-- render : True
-- environment : None
-- backend : VAE_LSTM
-- encoding : V_ONLY
-- n : None
-------------------------------

Compatible C models:
navreptrainencodedenv_2020_09_17__09_15_17_PPO_VAE_LSTM_V_ONLY_V32M512_ckpt.zip
navreptrainencodedenv_2020_09_19__13_27_16_PPO_VAE_LSTM_V_ONLY_V32M512_ckpt.zip
navreptrainencodedenv_2020_09_22__01_14_06_PPO_VAE_LSTM_V_ONLY_V32M512_ckpt.zip

  0%|                                                                                                                                                                        | 0/3 [00:00<?, ?it/s]C Model '/home/tutu/navrep/models/gym/navreptrainencodedenv_2020_09_17__09_15_17_PPO_VAE_LSTM_V_ONLY_V32M512_ckpt.zip' selected
/home/tutu/navrepvenv/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/rnn.py:85: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:32: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:40: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:44: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0999ce908>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0988f5748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7fd0988f5748>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:58: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:61: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fd098992e48>>: AssertionError: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:71: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2DTranspose` instead.
WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv2DTranspose.call of <tensorflow.python.layers.convolutional.Conv2DTranspose object at 0x7fd0988ee208>>: AttributeError: module 'gast' has no attribute 'Num'
WARNING:tensorflow:From /home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/models/vae2d.py:122: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

2022-11-11 16:58:51.825066: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2022-11-11 16:58:51.835343: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2112000000 Hz
2022-11-11 16:58:51.837113: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x83e3410 executing computations on platform Host. Devices:
2022-11-11 16:58:51.837227: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2022-11-11 16:58:51.931099: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
  0%|                                                                                                                                                                        | 0/3 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/navrep/scripts/cross_test_navreptrain_in_ianenv.py", line 101, in <module>
    c_model = PPO2.load(c_model_path)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 936, in load
    data, params = cls._load_from_file(load_path, custom_objects=custom_objects)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 666, in _load_from_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/stable_baselines/common/save_util.py", line 120, in json_to_data
    base64.b64decode(serialization.encode())
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 384, in <module>
    class CloudPickler(Pickler):
  File "/home/tutu/navrepvenv/lib/python3.6/site-packages/cloudpickle/cloudpickle_fast.py", line 406, in CloudPickler
    dispatch[types.CellType] = _cell_reduce
AttributeError: module 'types' has no attribute 'CellType'

**Comment by Yuanzizizi** [comment]
Here is my library list:

Package                       Version
----------------------------- ---------
absl-py                       1.3.0
actionlib                     1.13.2
angles                        1.9.13
asl-pepper-2d-sim             0.0.5
astor                         0.8.1
astunparse                    1.6.3
atari-py                      0.2.9
bondpy                        1.8.6
cached-property               1.5.2
cachetools                    4.2.4
camera-calibration            1.15.3
camera-calibration-parsers    1.12.0
catkin                        0.8.10
catkin-pkg                    0.5.2
certifi                       2022.9.24
charset-normalizer            2.0.12
cloudpickle                   1.2.0
commonmark                    0.9.1
controller-manager            0.19.5
controller-manager-msgs       0.19.5
cv-bridge                     1.15.0
cycler                        0.11.0
Cython                        0.29.32
dataclasses                   0.8
diagnostic-analysis           1.10.4
diagnostic-common-diagnostics 1.10.4
diagnostic-updater            1.10.4
docutils                      0.18.1
dynamic-reconfigure           1.7.1
future                        0.18.2
gast                          0.3.3
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.6.5
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.5.16
gennodejs                     2.0.2
genpy                         0.6.15
gitdb                         4.0.9
GitPython                     3.1.18
google-auth                   2.14.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.48.2
gym                           0.15.7
h5py                          2.10.0
idna                          3.4
image-geometry                1.15.0
importlib-metadata            4.8.3
importlib-resources           5.4.0
interactive-markers           1.12.0
joblib                        1.1.1
joint_state_publisher         1.15.0
joint_state_publisher_gui     1.15.0
Keras                         2.3.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
kiwisolver                    1.3.1
laser_geometry                1.6.7
llvmlite                      0.36.0
Markdown                      3.3.7
matplotlib                    3.3.4
message-filters               1.15.13
navrep                        0.0.18
numba                         0.53.1
numpy                         1.18.5
oauthlib                      3.2.2
opencv-python                 4.6.0.66
opt-einsum                    3.3.0
pandas                        1.1.5
Pillow                        8.4.0
pip                           21.3.1
pkg_resources                 0.0.0
protobuf                      3.19.6
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pyglet                        1.5.0
Pygments                      2.13.0
pyIAN                         0.0.3
pylidar2d                     0.1
pymap2d                       0.1.15
pyniel                        0.2
pyparsing                     3.0.9
pyrangelibc-danieldugas       0.0.2
pyrvo2-danieldugas            0.0.2
python-dateutil               2.8.2
python-qt-binding             0.4.4
pytz                          2022.6
PyYAML                        6.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
requests                      2.27.1
requests-oauthlib             1.3.1
resource_retriever            1.12.6
rich                          12.6.0
rosbag                        1.15.13
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.15.13
roslaunch                     1.15.13
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.15.13
rosmake                       1.15.8
rosmaster                     1.15.13
rosmsg                        1.15.13
rosnode                       1.15.13
rosparam                      1.15.13
rospkg                        1.4.0
rospy                         1.15.13
rosservice                    1.15.13
rostest                       1.15.13
rostopic                      1.15.13
rosunit                       1.15.8
roswtf                        1.15.13
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt_console                   0.4.11
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.2
rqt_gui_py                    0.5.2
rqt_image_view                0.4.16
rqt_launch                    0.4.9
rqt_logger_level              0.4.11
rqt-moveit                    0.5.10
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.2
rqt_py_console                0.4.10
rqt-reconfigure               0.5.4
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.13
rqt_robot_steering            0.5.12
rqt_runtime_monitor           0.5.9
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt_tf_tree                   0.6.2
rqt_top                       0.4.10
rqt_topic                     0.4.12
rqt_web                       0.4.10
rsa                           4.9
rviz                          1.14.10
scipy                         1.5.4
sensor-msgs                   1.13.1
setuptools                    59.6.0
six                           1.16.0
smach                         2.5.0
smach-ros                     2.5.0
smclib                        1.8.6
smmap                         5.0.0
soadrl-crowdnav               0.0.3
stable-baselines              2.10.2
tensorboard                   1.14.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    1.14.0
tensorflow-estimator          1.14.0
termcolor                     1.1.0
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.5
tf2-kdl                       0.7.5
tf2-py                        0.7.5
tf2-ros                       0.7.5
topic-tools                   1.15.13
torch                         1.10.1
torchvision                   0.11.2
tqdm                          4.64.1
typing_extensions             4.1.1
urllib3                       1.26.12
Werkzeug                      2.0.3
wheel                         0.34.2
wrapt                         1.14.1
xacro                         1.14.10
zipp                          3.6.0
